Fix an error on an incomplete init of a structure [-Werror=missing-field-initializers]
This fix:
lib/interface/Py_lib/libInterface.c:48:3: error: missing initializer [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:48:3: error: (near initialization for ‘libInterface_methods[0].ml_doc’) [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:49:3: error: missing initializer [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:49:3: error: (near initialization for ‘libInterface_methods[1].ml_doc’) [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:50:3: error: missing initializer [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:50:3: error: (near initialization for ‘libInterface_methods[2].ml_doc’) [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:51:3: error: missing initializer [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:51:3: error: (near initialization for ‘libInterface_methods[3].ml_doc’) [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:52:3: error: missing initializer [-Werror=missing-field-initializers]
lib/interface/Py_lib/libInterface.c:52:3: error: (near initialization for ‘libInterface_methods[4].ml_flags’) [-Werror=missing-field-initializers]