Add GCC attribute to set as unused a parameter.
Fix this:
lib/interface/Py_lib/libInterface.c: In function ‘py_deserializeMessages’:
lib/interface/Py_lib/libInterface.c:120:44: error: unused parameter ‘self’ [-Werror=unused-parameter]
lib/interface/Py_lib/libInterface.c: In function ‘py_deserializeGroups’:
lib/interface/Py_lib/libInterface.c:168:42: error: unused parameter ‘self’ [-Werror=unused-parameter]
lib/interface/Py_lib/libInterface.c: In function ‘py_deserializeSymbols’:
lib/interface/Py_lib/libInterface.c:225:44: error: unused parameter ‘self’ [-Werror=unused-parameter]
lib/interface/Py_lib/libInterface.c: In function ‘deserializeSymbols’: