Remove useless parameter from deserializeMessage function [-Werror=unused-parameter]
This fix:
lib/interface/Interface.c: In function ‘deserializeMessages’:
lib/interface/Interface.c:66:125: error: unused parameter ‘sizeSerialMessages’ [-Werror=unused-parameter]