Remove useless parameter from deserializeMessages function [-Werror=unused-parameter]
This fix :
lib/interface/Interface.c: In function ‘deserializeMessages’:
lib/interface/Interface.c:66:69: error: unused parameter ‘sizeFormat’ [-Werror=unused-parameter]