Fix two small gcc errors regarding unused parameters (but required) and an unused variables (debug mode).
This fix:
lib/libNeedleman/Py_lib/libScoreComputation.c: In function ‘py_getHighestEquivalentGroup’:
lib/libNeedleman/Py_lib/libScoreComputation.c:67:8: error: variable ‘bool_debugMode’ set but not used [-Werror=unused-but-set-variable]
lib/libNeedleman/Py_lib/libScoreComputation.c:60:50: error: unused parameter ‘self’ [-Werror=unused-parameter]

Change-Id: I33c0678e697f7ddf049660edb4adeae81d57ffbf